openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /templates:
    get:
      tags:
      - TemplateResource
      operationId: getTemplate
      responses:
        200:
          description: Returns array of templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Template'
  /templates/{id}:
    get:
      tags:
        - TemplateResource
      operationId: getTemplateById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Returns template by identifier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
components:
  schemas:
    Template:
      type: object
      properties:
        name:
          type: string
